// <auto-generated />
using ActivosCatalogApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace INVENTARIO.Services.ActivosCatalogApi.Data.Migrations
{
    [DbContext(typeof(ActivosContext))]
    [Migration("20180305005629_ActivosDb")]
    partial class ActivosDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("Relational:Sequence:.CatalogActivos_hilo", "'CatalogActivos_hilo', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.TipoActivos_hilo", "'TipoActivos_hilo', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActivosCatalogApi.Domain.CatalogActivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "CatalogActivos_hilo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Acta_entrega")
                        .IsRequired();

                    b.Property<string>("Cod_institucion")
                        .IsRequired();

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Estado");

                    b.Property<DateTime>("Fecha_adquisicion");

                    b.Property<string>("Marca")
                        .IsRequired();

                    b.Property<string>("Observacion");

                    b.Property<decimal>("Precio_actual");

                    b.Property<decimal>("Precio_compra");

                    b.Property<string>("Serie_modelo")
                        .IsRequired();

                    b.Property<int>("TipoActivosID");

                    b.HasKey("Id");

                    b.HasIndex("TipoActivosID");

                    b.ToTable("CatalogActivos");
                });

            modelBuilder.Entity("ActivosCatalogApi.Domain.TipoActivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "TipoActivos_hilo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<int?>("CatalogActivosId");

                    b.Property<int>("Residual");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("VidaUtil");

                    b.HasKey("Id");

                    b.HasIndex("CatalogActivosId");

                    b.ToTable("TipoActivos");
                });

            modelBuilder.Entity("ActivosCatalogApi.Domain.CatalogActivos", b =>
                {
                    b.HasOne("ActivosCatalogApi.Domain.TipoActivos")
                        .WithMany()
                        .HasForeignKey("TipoActivosID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ActivosCatalogApi.Domain.TipoActivos", b =>
                {
                    b.HasOne("ActivosCatalogApi.Domain.CatalogActivos")
                        .WithMany("TipoActivos")
                        .HasForeignKey("CatalogActivosId");
                });
#pragma warning restore 612, 618
        }
    }
}
